version: '3'
services:
  mysql:
    image: mysql:8.0-debian
    container_name: api-mysql
    command: --skip-initialize-insecure
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT:-3306}:3306"
    networks:
      - mynetwork
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api-container
    depends_on:
      - mysql
    ports:
      - "${API_PORT:-3000}:3000"
    networks:
      - mynetwork
    volumes:
      - ./dist:/app/dist
    command: ["./scripts/wait-for-it.sh","-t", "120", "mysql:3306", "--", "./scripts/start-api.sh"]
    environment:
      DB_HOST: mysql
      DB_PORT: "${DB_PORT:-3306}"
      DB_USER: root
      DB_PASS: "${DB_PASS}"

networks:
  mynetwork:
   

volumes:
  mysql_data:
