# Use the official Node.js image
FROM node:20

# Create a directory where our app will be placed
WORKDIR /app

# Copy the file from your host to your current location

COPY package.json package-lock.json .sequelizerc .env /app/

COPY /config/sequelizeCli.js /app/config/

COPY ./scripts /app/scripts

COPY ./dist /app/dist

# Install production dependencies
RUN npm install --only=production

# Expose port 3000
EXPOSE 3000
